# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 87bb0893eca9de55115cf8f8cc3933aba4d2949df612766b75fd479cc532cb06a99611dc6b130b1815e36ab00f1828a511bc561d09c6283f4e14ee0d50335a74

test:
  secret_key_base: 03c214ab72361323578dce8f71082d992770297e27900ee553d0ad18ddadf8adbe85d664cf370547e2de442615f23b18da907ab8bc63bb6da71b32be26709496

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
